runtime: python
env: flex
entrypoint: gunicorn -b :$PORT codingal.wsgi

runtime_config:
  python_version: 3
  
manual_scaling:
  instances: 1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

